# ipcs_common/atomic
# Author: feimat@qq.com
# Date: 01/28/2013
cc_test(
    name='atomic_test',
    srcs=[
        'atomic_test.cpp'
    ],
    deps=[
        '//thirdparty/gtest:gtest'
    ],
    heap_check='strict'
)
