# Jack
cc_library(
    name='collections',
    srcs=[
    ],
    deps=[
        '//ipcs_common/base/string:ipcs_string',
        '//ipcs_common/crypto/hash:hash'
    ]
)

cc_test(
    name = 'prefix_map_test',
    srcs = [
        'prefix_map_test.cpp'
    ],
    deps = [
        ':collections',
    ]
)
