# ipcs_common/system
# Author: feimat@qq.com
# Date: 02/20/2013
cc_library(
    name='check_error',
    srcs='check_error.cpp',
    deps=[]
)

cc_test(
    name='check_error_test',
    srcs='check_error_test.cpp',
    deps=[
        ':check_error',
        '//thirdparty/gtest:gtest'
    ],
    heap_check='strict'
)
