EXE := libcomm.a

SOURCE :=  $(wildcard *.c) $(wildcard *.cpp)
OBJS   :=  $(patsubst %.c,%.o,$(patsubst %.cpp,%.o,$(SOURCE)))

all: $(OBJS)
	$(AR) r $(EXE) $^

clean:
	rm -f $(OBJS) $(EXE)

install:
	mv -f $(EXE) ../lib
	cp -f *.h ../include
