LDFLAGS	:= 	-L$(COMM_LIB_DIR) -lcomm
ODFLAGS :=	../comm/libcomm.a
CGI_BINARIES:= getlog transunicode getmsg
INC_DIR=-I../comm/
CFLAGS= -Wall -DUNIX -g -Wno-deprecated -D_REENTRANT

all: $(CGI_BINARIES)

getlog: getlog.o
	$(CXX) -g -o $@ $^ $(ODFLAGS) $(LDFLAGS) -lpthread
getmsg: getmsg.o
	$(CXX) -g -o $@ $^ $(ODFLAGS) $(LDFLAGS) -lpthread
transunicode: transunicode.o
	$(CXX) -g -o $@ $^ $(ODFLAGS) $(LDFLAGS) -lpthread
clean:
	rm $(CGI_BINARIES) *.o *.cgi -f
%.o: %.cpp
	$(CXX) $(CFLAGS) $(INC_DIR) -c $< -o $@

install:
	#cp getlog.cgi /home/work/apache/cgi-bin/ -f
	cp getmsg.cgi /home/work/apache/cgi-bin/ -f

